name: neur299
dependencies:
- pip:
  - jupyterhub
  - jupyter
  - matplotlib==1.5.3
  - numpy==1.11.3
  - pandas==0.19.2
  - scikit-learn==0.18.1
  - scipy==0.18.1
  - seaborn==0.7.1
  - statsmodels==0.6.1
